- name: Copy files to archive
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Grab json file
      ansible.builtin.set_fact:
        old_files: "{{ lookup('ansible.builtin.file', 'data/old_files.json') }}"
        # old_files:
          # [{
          #   "file_name": "5051_11_Paper_Chase_3_–_No_Need_To_Irrigate_Abscesses_MM_CN_sps.pdf",
          #   "lastWriteTime": "2018-01-15T05:01:53.336230+00:00",
          #   "topic_description": "Paper Chase 3 - No Need To Irrigate Abscesses",
          #   "topic_id": 5051
          # }]

    - name: Test each file
      ansible.builtin.include_tasks: tasks/copy_each_file_to_archive.yml
      loop: "{{ old_files  }}"
      loop_control:
        loop_var: file
      vars:
        azcopy_flags: '--dry-run --output-type "json"'

    - name: Throw up warning message
      ansible.builtin.debug:
        msg: |
          You are about to copy {{ old_files | length }} files from
          {{ source_storage_url }}/{{ source_share_path }}
          to
          {{ dest_storage_url }}
          Are you sure?
    - name: Make sure
      ansible.builtin.pause:

    - name: Copy each file
      ansible.builtin.include_tasks: tasks/copy_each_file_to_archive.yml
      loop: "{{ old_files  }}"
      loop_control:
        loop_var: file
      vars:
        azcopy_flags: '--output-type "json"'
