- name: Remove files from share
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Grab json file
      ansible.builtin.set_fact:
        old_files: "{{ lookup('ansible.builtin.file', 'data/old_files.json') }}"
        # old_files:
        #   [{
        #     "file_name": "5051_EMRAP_2016_Feb_Track13_PC3_Irrigate.mp3",
        #     "lastWriteTime": "2018-01-15T05:01:54.024881+00:00",
        #     "topic_description": "Paper Chase 3 - No Need To Irrigate Abscesses",
        #     "topic_id": 5051
        #   }]

    - name: Test each file
      ansible.builtin.include_tasks: tasks/delete_each_file.yml
      loop: "{{ old_files  }}"
      loop_control:
        loop_var: file
      vars:
        azcli_flags: '--dry-run --output-type "json"'

    - name: Throw up warning message
      ansible.builtin.debug:
        msg: |
          You are about to delete {{ old_files | length }} files from
          {{ source_storage_url }}/{{ source_share_path }}
          Are you sure?
    - name: Make sure
      ansible.builtin.pause:

    - name: Delete each file
      ansible.builtin.include_tasks: tasks/delete_each_file.yml
      loop: "{{ old_files  }}"
      loop_control:
        loop_var: file
      vars:
        azcli_flags: '--output-type "json"'
